#!/usr/bin/env node
/**
 * Vendors the three webfonts into src/assets/fonts/ and writes the
 * @font-face rules that go with them (src/styles/fonts.css).
 *
 * Loading them from fonts.gstatic.com meant the display type reflowed when
 * the files finally arrived — a 0.07 layout shift on the hero, every first
 * visit. Self-hosting puts the files on the same origin as the bundle, so
 * they can be preloaded and are already cached with it, and it drops a
 * third-party connection from the critical path.
 *
 * All three faces are OFL-licensed, which permits redistribution.
 *
 * Usage: node scripts/gen-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const FONT_DIR = path.join(ROOT, 'src', 'assets', 'fonts');
const OUT_CSS = path.join(ROOT, 'src', 'styles', 'fonts.css');

/** The site is RU-default with UZ (Latin) and EN, so these four subsets. */
const WANTED = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

const FAMILIES = [
  { family: 'Unbounded', weights: [400] },
  { family: 'Onest', weights: [400, 500] },
  { family: 'JetBrains Mono', weights: [400, 500] },
];

// A modern UA is required or the API answers with .ttf instead of .woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

mkdirSync(FONT_DIR, { recursive: true });

const blocks = [];

for (const { family, weights } of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, '+')}:wght@${weights.join(';')}&display=swap`;
  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text());

  // The response is a run of `/* subset */ @font-face { ... }` blocks.
  const faces = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)];

  for (const [, subset, body] of faces) {
    if (!WANTED.has(subset)) continue;
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const src = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (!weight || !src || !range) continue;

    const slug = `${family.toLowerCase().replace(/ /g, '-')}-${weight}-${subset}.woff2`;
    const bytes = Buffer.from(await fetch(src).then((r) => r.arrayBuffer()));
    writeFileSync(path.join(FONT_DIR, slug), bytes);

    blocks.push(
      `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('../assets/fonts/${slug}') format('woff2');\n  unicode-range: ${range};\n}`,
    );
    console.log(`${slug}  ${(bytes.length / 1024).toFixed(1)} kB`);
  }
}

writeFileSync(
  OUT_CSS,
  `/* AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
   Self-hosted so the display type does not reflow when the files land, and
   so the page makes no third-party font request. All three families are
   OFL-licensed. Re-run the script to refresh. */

${blocks.join('\n\n')}
`,
  'utf8',
);

console.log(`\nwrote ${blocks.length} @font-face rules to ${path.relative(ROOT, OUT_CSS)}`);
